version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile_python_flask
    tty: true
    command: /bin/sh "gunicorn.sh"
    restart: always
    volumes:
      - ./:/app
    working_dir: /app
    expose:
      - 5000
    networks:
      - backend
    depends_on:
      - nginx

  nginx:
    image: nginx
    tty: true
    restart: always
    volumes:
      - ./:/app
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
