version: '3.3'

services:
  php:
    build: .
    command: /bin/bash -c "php -S 0.0.0.0:8080 -t public"
    volumes:
      - ./:/var/www/
      - ./:/var/www/html/
    ports:
     - 127.0.0.1:8080:8080
    depends_on:
      - mysql
    networks:
      - backend

  queue:
    build: .
    command: bash -c 'php artisan queue:listen --timeout=5000; tail -f /dev/null'
    volumes:
      - ./:/var/www/
    depends_on:
      - php
    networks:
      - backend

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - backend

networks:
  backend:
    driver: bridge
